version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: garrowd/coffeemachine-app:latest
    container_name: coffeemachine
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      POSTGRESDB_URL: postgres:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-data:
    driver: local
