spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESDB_URL:localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    show-sql: false
    hibernate:
      ddl-auto: validate

  flyway:
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${POSTGRESDB_URL:localhost:5432/postgres}
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /docs/doc
  swagger-ui:
    path: /docs/doc-ui

logging:
  level:
    root: info